// <auto-generated />
using BeerGenius.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeerGenius.Migrations
{
    [DbContext(typeof(BeerGeniusDbContext))]
    [Migration("20190902233801_Adding user flavor profile")]
    partial class Addinguserflavorprofile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeerGenius.Models.FlavorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ABV");

                    b.Property<int>("Aroma");

                    b.Property<int>("Color");

                    b.Property<int>("Crisp");

                    b.Property<int>("Fruity");

                    b.Property<int>("Hop");

                    b.Property<int>("Malt");

                    b.Property<int>("Roasty");

                    b.Property<int>("Sour");

                    b.Property<int>("Sweetness");

                    b.HasKey("Id");

                    b.ToTable("FlavorProfiles");

                    b.HasData(
                        new
                        {
                            Id = 66,
                            ABV = 6,
                            Aroma = 1,
                            Color = 2,
                            Crisp = 7,
                            Fruity = 10,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 0,
                            Sour = 6,
                            Sweetness = 6
                        },
                        new
                        {
                            Id = 43,
                            ABV = 8,
                            Aroma = 10,
                            Color = 10,
                            Crisp = 0,
                            Fruity = 1,
                            Hop = 5,
                            Malt = 10,
                            Roasty = 8,
                            Sour = 0,
                            Sweetness = 4
                        },
                        new
                        {
                            Id = 75,
                            ABV = 3,
                            Aroma = 3,
                            Color = 1,
                            Crisp = 8,
                            Fruity = 1,
                            Hop = 4,
                            Malt = 2,
                            Roasty = 0,
                            Sour = 0,
                            Sweetness = 1
                        },
                        new
                        {
                            Id = 60,
                            ABV = 10,
                            Aroma = 7,
                            Color = 3,
                            Crisp = 0,
                            Fruity = 8,
                            Hop = 3,
                            Malt = 8,
                            Roasty = 4,
                            Sour = 0,
                            Sweetness = 7
                        });
                });

            modelBuilder.Entity("BeerGenius.Models.UserFlavorProfile", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ABV");

                    b.Property<int>("Aroma");

                    b.Property<int>("Color");

                    b.Property<int>("Crisp");

                    b.Property<int>("Fruity");

                    b.Property<int>("Hop");

                    b.Property<int>("Malt");

                    b.Property<int>("Roasty");

                    b.Property<int>("Sour");

                    b.Property<int>("Sweetness");

                    b.HasKey("UserId");

                    b.ToTable("UserFlavorProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
