// <auto-generated />
using BeerGenius.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeerGenius.Migrations
{
    [DbContext(typeof(BeerGeniusDbContext))]
    [Migration("20190910000030_Added TimesMatched into FlavorProfile")]
    partial class AddedTimesMatchedintoFlavorProfile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeerGenius.Models.BeerGeniusUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("BeerGeniusUsers");
                });

            modelBuilder.Entity("BeerGenius.Models.FlavorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ABV");

                    b.Property<int>("BreweryDbId");

                    b.Property<int>("Color");

                    b.Property<int>("Crisp");

                    b.Property<int>("Fruity");

                    b.Property<int>("Hop");

                    b.Property<int>("Malt");

                    b.Property<int>("Roasty");

                    b.Property<int>("Sour");

                    b.Property<int>("Sweetness");

                    b.Property<int>("TimesSelected");

                    b.HasKey("Id");

                    b.ToTable("FlavorProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ABV = 2,
                            BreweryDbId = 1,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 3,
                            Malt = 2,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 2,
                            ABV = 2,
                            BreweryDbId = 2,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 3,
                            Hop = 3,
                            Malt = 2,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 3,
                            ABV = 2,
                            BreweryDbId = 3,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 3,
                            Malt = 2,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 4,
                            ABV = 2,
                            BreweryDbId = 4,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 3,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 5,
                            ABV = 2,
                            BreweryDbId = 5,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 3,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 6,
                            ABV = 2,
                            BreweryDbId = 6,
                            Color = 1,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 3,
                            Malt = 1,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 7,
                            ABV = 1,
                            BreweryDbId = 7,
                            Color = 1,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 8,
                            ABV = 1,
                            BreweryDbId = 8,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 9,
                            ABV = 1,
                            BreweryDbId = 9,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 10,
                            ABV = 1,
                            BreweryDbId = 10,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 11,
                            ABV = 1,
                            BreweryDbId = 11,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 12,
                            ABV = 2,
                            BreweryDbId = 12,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 13,
                            ABV = 2,
                            BreweryDbId = 13,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 14,
                            ABV = 3,
                            BreweryDbId = 14,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 15,
                            ABV = 3,
                            BreweryDbId = 15,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 3,
                            Sour = 1,
                            Sweetness = 3,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 16,
                            ABV = 3,
                            BreweryDbId = 16,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 17,
                            ABV = 3,
                            BreweryDbId = 17,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 3,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 18,
                            ABV = 2,
                            BreweryDbId = 18,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 19,
                            ABV = 2,
                            BreweryDbId = 19,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 20,
                            ABV = 2,
                            BreweryDbId = 20,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 3,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 21,
                            ABV = 2,
                            BreweryDbId = 21,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 3,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 22,
                            ABV = 2,
                            BreweryDbId = 22,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 23,
                            ABV = 2,
                            BreweryDbId = 23,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 3,
                            Malt = 3,
                            Roasty = 3,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 24,
                            ABV = 3,
                            BreweryDbId = 24,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 3,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 25,
                            ABV = 2,
                            BreweryDbId = 25,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 3,
                            Hop = 3,
                            Malt = 2,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 26,
                            ABV = 2,
                            BreweryDbId = 29,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 3,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 27,
                            ABV = 2,
                            BreweryDbId = 30,
                            Color = 2,
                            Crisp = 3,
                            Fruity = 2,
                            Hop = 3,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 28,
                            ABV = 3,
                            BreweryDbId = 31,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 3,
                            Hop = 3,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 29,
                            ABV = 2,
                            BreweryDbId = 32,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 30,
                            ABV = 3,
                            BreweryDbId = 33,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 3,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 31,
                            ABV = 3,
                            BreweryDbId = 34,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 3,
                            Hop = 3,
                            Malt = 3,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 32,
                            ABV = 3,
                            BreweryDbId = 35,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 3,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 33,
                            ABV = 2,
                            BreweryDbId = 36,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 34,
                            ABV = 2,
                            BreweryDbId = 37,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 35,
                            ABV = 2,
                            BreweryDbId = 38,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 36,
                            ABV = 2,
                            BreweryDbId = 41,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 3,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 37,
                            ABV = 2,
                            BreweryDbId = 42,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 3,
                            Malt = 2,
                            Roasty = 3,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 38,
                            ABV = 3,
                            BreweryDbId = 43,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 3,
                            Malt = 3,
                            Roasty = 3,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 39,
                            ABV = 3,
                            BreweryDbId = 44,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 40,
                            ABV = 2,
                            BreweryDbId = 45,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 41,
                            ABV = 1,
                            BreweryDbId = 46,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 2,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 42,
                            ABV = 2,
                            BreweryDbId = 47,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 3,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 3,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 43,
                            ABV = 2,
                            BreweryDbId = 48,
                            Color = 1,
                            Crisp = 2,
                            Fruity = 3,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 2,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 44,
                            ABV = 2,
                            BreweryDbId = 49,
                            Color = 1,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 2,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 45,
                            ABV = 1,
                            BreweryDbId = 50,
                            Color = 1,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 46,
                            ABV = 2,
                            BreweryDbId = 51,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 47,
                            ABV = 2,
                            BreweryDbId = 52,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 48,
                            ABV = 3,
                            BreweryDbId = 53,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 49,
                            ABV = 2,
                            BreweryDbId = 54,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 3,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 50,
                            ABV = 2,
                            BreweryDbId = 55,
                            Color = 2,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 51,
                            ABV = 2,
                            BreweryDbId = 57,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 2,
                            Sour = 3,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 52,
                            ABV = 2,
                            BreweryDbId = 58,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 2,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 53,
                            ABV = 3,
                            BreweryDbId = 59,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 2,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 54,
                            ABV = 3,
                            BreweryDbId = 60,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 3,
                            Hop = 2,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 2,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 55,
                            ABV = 2,
                            BreweryDbId = 61,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 56,
                            ABV = 2,
                            BreweryDbId = 62,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 57,
                            ABV = 3,
                            BreweryDbId = 63,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 3,
                            Hop = 2,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 3,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 58,
                            ABV = 3,
                            BreweryDbId = 64,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 3,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 3,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 59,
                            ABV = 2,
                            BreweryDbId = 65,
                            Color = 1,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 60,
                            ABV = 2,
                            BreweryDbId = 66,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 3,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 2,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 61,
                            ABV = 2,
                            BreweryDbId = 67,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 3,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 3,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 62,
                            ABV = 2,
                            BreweryDbId = 68,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 3,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 3,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 63,
                            ABV = 1,
                            BreweryDbId = 69,
                            Color = 2,
                            Crisp = 3,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 2,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 64,
                            ABV = 2,
                            BreweryDbId = 71,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 3,
                            Sour = 2,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 65,
                            ABV = 2,
                            BreweryDbId = 72,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 2,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 66,
                            ABV = 2,
                            BreweryDbId = 73,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 3,
                            Hop = 3,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 67,
                            ABV = 2,
                            BreweryDbId = 74,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 3,
                            Hop = 2,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 68,
                            ABV = 2,
                            BreweryDbId = 75,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 69,
                            ABV = 2,
                            BreweryDbId = 76,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 70,
                            ABV = 1,
                            BreweryDbId = 77,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 71,
                            ABV = 2,
                            BreweryDbId = 78,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 72,
                            ABV = 2,
                            BreweryDbId = 79,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 73,
                            ABV = 2,
                            BreweryDbId = 80,
                            Color = 2,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 74,
                            ABV = 2,
                            BreweryDbId = 81,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 75,
                            ABV = 2,
                            BreweryDbId = 82,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 76,
                            ABV = 2,
                            BreweryDbId = 83,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 77,
                            ABV = 2,
                            BreweryDbId = 84,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 78,
                            ABV = 2,
                            BreweryDbId = 85,
                            Color = 2,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 79,
                            ABV = 2,
                            BreweryDbId = 86,
                            Color = 1,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 3,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 80,
                            ABV = 2,
                            BreweryDbId = 88,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 3,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 81,
                            ABV = 2,
                            BreweryDbId = 89,
                            Color = 1,
                            Crisp = 1,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 82,
                            ABV = 3,
                            BreweryDbId = 90,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 3,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 83,
                            ABV = 2,
                            BreweryDbId = 93,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 84,
                            ABV = 1,
                            BreweryDbId = 94,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 85,
                            ABV = 1,
                            BreweryDbId = 95,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 86,
                            ABV = 2,
                            BreweryDbId = 98,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 87,
                            ABV = 2,
                            BreweryDbId = 101,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 88,
                            ABV = 2,
                            BreweryDbId = 102,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 2,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 89,
                            ABV = 2,
                            BreweryDbId = 103,
                            Color = 3,
                            Crisp = 2,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 1,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 90,
                            ABV = 3,
                            BreweryDbId = 104,
                            Color = 3,
                            Crisp = 1,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 3,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 91,
                            ABV = 1,
                            BreweryDbId = 105,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 92,
                            ABV = 2,
                            BreweryDbId = 109,
                            Color = 1,
                            Crisp = 3,
                            Fruity = 1,
                            Hop = 1,
                            Malt = 1,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 93,
                            ABV = 2,
                            BreweryDbId = 114,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 3,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 1,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 94,
                            ABV = 3,
                            BreweryDbId = 115,
                            Color = 2,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 95,
                            ABV = 3,
                            BreweryDbId = 116,
                            Color = 3,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        },
                        new
                        {
                            Id = 96,
                            ABV = 3,
                            BreweryDbId = 117,
                            Color = 3,
                            Crisp = 2,
                            Fruity = 2,
                            Hop = 1,
                            Malt = 2,
                            Roasty = 2,
                            Sour = 1,
                            Sweetness = 2,
                            TimesSelected = 0
                        });
                });

            modelBuilder.Entity("BeerGenius.Models.UserFlavorProfile", b =>
                {
                    b.Property<int>("UserFlavorProfileId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ABV");

                    b.Property<int>("Color");

                    b.Property<int>("Crisp");

                    b.Property<int>("Fruity");

                    b.Property<int>("Hop");

                    b.Property<int>("Malt");

                    b.Property<int>("MatchingFlavorProfileId");

                    b.Property<int>("Roasty");

                    b.Property<int>("Sour");

                    b.Property<int>("Sweetness");

                    b.Property<int>("UserId");

                    b.HasKey("UserFlavorProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFlavorProfiles");
                });

            modelBuilder.Entity("BeerGenius.Models.UserFlavorProfile", b =>
                {
                    b.HasOne("BeerGenius.Models.BeerGeniusUser", "BeerGeniusUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
